# Generated by Django 3.0.8 on 2021-05-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(default='waiting', max_length=32),
        ),
        migrations.AlterField(
            model_name='room',
            name='interval',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
